/** Numbered bibliography for inline [n] references across the site. */
export const CITATIONS = [
  {
    num: 1,
    id: 'nrel-market-2025',
    title: '2025 U.S. Geothermal Market Report',
    org: 'National Renewable Energy Laboratory',
    year: 2025,
    url: 'https://docs.nrel.gov/docs/fy26osti/91898.pdf',
    note: 'U.S. capacity, employment, technology trends, and project timelines.',
  },
  {
    num: 2,
    id: 'irena-geothermal',
    title: 'Geothermal power',
    org: 'International Renewable Energy Agency',
    year: 2024,
    url: 'https://www.irena.org/Energy-Transition/Technology/geothermal',
    note: 'Global installed capacity and cost trends.',
  },
  {
    num: 3,
    id: 'doe-geode',
    title: 'DOE invests in advancing domestic geothermal energy deployment (GEODE)',
    org: 'U.S. Department of Energy',
    year: 2024,
    url: 'https://www.energy.gov/articles/doe-invest-165-million-advance-domestic-geothermal-energy-deployment',
    note: 'Oil-and-gas-adjacent workforce transferable to geothermal drilling.',
  },
  {
    num: 4,
    id: 'smu-heat-flow',
    title: 'SMU Geothermal Laboratory heat-flow maps and database',
    org: 'Southern Methodist University',
    year: null,
    url: 'https://www.smu.edu/Dedman/Academics/Departments/Earth-Sciences/Research/GeothermalLab',
    note: 'Continental heat flow and geothermal gradient context for the U.S.',
  },
  {
    num: 5,
    id: 'usgs-geothermal-basics',
    title: 'Geothermal energy — the Earth\'s heat',
    org: 'U.S. Geological Survey',
    year: null,
    url: 'https://www.usgs.gov/programs/energy-resources-program/science/geothermal-energy-earths-heat',
    note: 'Background on geothermal gradients and resource types.',
  },
  {
    num: 6,
    id: 'orkustofnun-direct-use',
    title: 'Direct use of geothermal energy in Iceland',
    org: 'National Energy Authority of Iceland (Orkustofnun)',
    year: null,
    url: 'https://orkustofnun.is/en/category/direct-utilization',
    note: 'District heating and direct-use deployment at national scale.',
  },
  {
    num: 7,
    id: 'nbmg-geothermal-hub',
    title: 'NBMG Geothermal Energy program',
    org: 'Nevada Bureau of Mines and Geology, University of Nevada, Reno',
    year: null,
    url: 'https://nbmg.unr.edu/geothermal/index.html',
    note: 'Great Basin maps, data, publications, and regional exploration resources.',
  },
  {
    num: 8,
    id: 'nbmg-great-basin-gis',
    title: 'Great Basin geothermal GIS data downloads',
    org: 'Nevada Bureau of Mines and Geology',
    year: null,
    url: 'https://nbmg.unr.edu/geothermal/data.html',
    note: 'Downloadable layers: geology, geochemistry, BLM leases, hot springs, favorability, geophysics.',
  },
  {
    num: 9,
    id: 'unr-subsurface-explorer',
    title: 'UNR Subsurface Database Explorer (Keck Library)',
    org: 'University of Nevada, Reno',
    year: null,
    url: 'https://keck-nbmg.opendata.arcgis.com/',
    note: 'Current Nevada subsurface records and open geospatial data.',
  },
  {
    num: 10,
    id: 'nbmg-gbggdb',
    title: 'Great Basin Groundwater Geochemical Database',
    org: 'Nevada Bureau of Mines and Geology',
    year: null,
    url: 'https://nbmg.unr.edu/Geothermal/GeochemDatabase.html',
    note: 'Regional fluid chemistry for exploration and geothermometry.',
  },
  {
    num: 11,
    id: 'nbmg-thermal-waters',
    title: 'Thermal Waters of Nevada',
    org: 'Nevada Bureau of Mines and Geology Bulletin 91',
    year: 1979,
    url: 'https://pubs.nbmg.unr.edu/Thermal-waters-of-Nevada-p/b091.htm',
    note: 'Foundational catalog of Nevada hot springs, wells, chemistry, and exploration history.',
  },
  {
    num: 12,
    id: 'nbmg-ofr-2012-03',
    title: 'Data Tables and Graphs of Geothermal Power Production in Nevada, 1985–2011',
    org: 'NBMG Open-File Report 2012-03',
    year: 2012,
    url: 'https://pubs.nbmg.unr.edu/Data-tables-and-graphs-p/of2012-03.htm',
    note: 'Historical Nevada plant production data.',
  },
  {
    num: 13,
    id: 'nbmg-well-file-index',
    title: 'Index to geothermal well files housed at NBMG',
    org: 'NBMG Report L-5',
    year: null,
    url: 'https://pubs.nbmg.unr.edu/Index-geoth-well-files-2009-p/l005.htm',
    note: 'Well file archive index for Nevada geothermal drilling records.',
  },
  {
    num: 14,
    id: 'noaa-thermal-springs',
    title: 'NOAA thermal springs database',
    org: 'NOAA National Centers for Environmental Information',
    year: null,
    url: 'https://www.ngdc.noaa.gov/nndc/servlet/ShowDatasets?dataset=100006',
    note: 'U.S. thermal spring locations and attributes for reconnaissance.',
  },
  {
    num: 15,
    id: 'usgs-of99-425',
    title: 'Maps and data showing geographic distribution of subsurface temperatures in the Great Basin',
    org: 'USGS Open-File Report 99-425',
    year: 1999,
    url: 'https://pubs.usgs.gov/of/1999/of99-425/',
    note: 'Historic Great Basin drill-hole temperature profiles.',
  },
  {
    num: 16,
    id: 'gbcge',
    title: 'Great Basin Center for Geothermal Energy',
    org: 'University of Nevada, Reno',
    year: null,
    url: 'https://gbcge.org/',
    note: 'Regional research, exploration synthesis, and National Geothermal Academy.',
  },
  {
    num: 17,
    id: 'nv-division-minerals',
    title: 'Nevada Division of Minerals — geothermal updates',
    org: 'State of Nevada',
    year: null,
    url: 'https://minerals.nv.gov/',
    note: 'State leasing, drilling, and geothermal activity reporting.',
  },
  {
    num: 18,
    id: 'doe-seismicity-protocol',
    title: 'DOE Induced Seismicity Protocol for geothermal projects',
    org: 'U.S. Department of Energy',
    year: null,
    url: 'https://www.energy.gov/hgeo/geothermal/articles/doe-releases-updated-induced-seismicity-protocol',
    note: 'Traffic-light monitoring requirements for stimulation projects.',
  },
  {
    num: 19,
    id: 'iea-utes',
    title: 'Underground thermal energy storage (IEA Energy Storage TCP)',
    org: 'International Energy Agency',
    year: null,
    url: 'https://iea-es.org/activities/underground-thermal-energy-storage-utes/',
    note: 'ATES/BTES case summaries, recovery rates, and international deployment context.',
  },
  {
    num: 20,
    id: 'drake-landing',
    title: 'Drake Landing Solar Community',
    org: 'Natural Resources Canada / project partners',
    year: null,
    url: 'https://www.nrcan.gc.ca/energy/energy-sources/renewable-energy/publications/6427',
    note: 'Reference BTES + solar thermal district heating project in Alberta.',
  },
  {
    num: 21,
    id: 'lbl-permitting',
    title: 'Environmental law and permitting for geothermal energy development',
    org: 'Lawrence Berkeley National Laboratory',
    year: null,
    url: 'https://eta-publications.lbl.gov/sites/default/files/elaw_geothermal_permitting.pdf',
    note: 'Federal and state permitting pathways and typical schedule accumulation.',
  },
  {
    num: 22,
    id: 'georeport',
    title: 'GeoRePORT geothermal resource classification and reporting',
    org: 'National Renewable Energy Laboratory',
    year: 2022,
    url: 'https://www.nrel.gov/docs/fy22osti/81820.pdf',
    note: 'Standard framework for describing geothermal resource characteristics.',
  },
  {
    num: 23,
    id: 'iddp-iceland',
    title: 'Iceland Deep Drilling Project (IDDP)',
    org: 'IDDP consortium',
    year: null,
    url: 'https://www.iddp.is/',
    note: 'Superhot and supercritical drilling research at Krafla and Reykjanes.',
  },
  {
    num: 24,
    id: 'unr',
    title: 'University of Nevada, Reno',
    org: 'University of Nevada, Reno',
    year: null,
    url: 'https://www.unr.edu/',
    note: 'Home institution for NBMG, the Great Basin Center for Geothermal Energy, and the Keck subsurface data program.',
  },
  {
    num: 25,
    id: 'nbmg-publications',
    title: 'NBMG Publications',
    org: 'Nevada Bureau of Mines and Geology',
    year: null,
    url: 'https://pubs.nbmg.unr.edu/',
    note: 'Bulletins, open-file reports, and lists including Thermal Waters of Nevada and geothermal well file indexes.',
  },
  {
    num: 26,
    id: 'sandia-drilling-handbook',
    title: 'Handbook of Best Practices for Geothermal Drilling',
    org: 'Sandia National Laboratories (SAND2011-6478)',
    year: 2012,
    url: 'https://www.osti.gov/servlets/purl/1325261',
    note: 'Finger and Blankenship. Rig selection, casing and cement, mud programs, lost circulation, well control, logging, and high-temperature tooling. Prepared for the IEA Geothermal Implementing Agreement.',
  },
  {
    num: 27,
    id: 'calgem-bope',
    title: 'Blowout Prevention in California (CalGEM Instruction Manual M07)',
    org: 'California Geologic Energy Management Division',
    year: 2006,
    url: 'https://www.conservation.ca.gov/calgem/pubs_stats/Pages/instruction_manuals.aspx',
    note: 'State BOPE functions, operating characteristics, and geothermal well requirements in California. H\u2082S drilling manual M10 is on the same page.',
  },
  {
    num: 28,
    id: 'pact-initiative',
    title: 'Partnerships for Academic-Industry Career Training (PACT) Initiative',
    org: 'U.S. Department of Energy HGEO & Office of Indian Energy (via TechWerx)',
    year: 2026,
    url: 'https://www.energy.gov/hgeo/funding-notice-partnerships-academic-industry-career-training-pact',
    note: 'Up to $11.3M for regional academic-industry consortia to build hands-on training and stackable credentials in oil, gas, coal, and geothermal energy careers. Up to $2.3M reserved for Tribal Colleges and Universities.',
  },
  {
    num: 29,
    id: 'hgeo-workforce-programs',
    title: 'HGEO Workforce Programs',
    org: 'U.S. Department of Energy Hydrocarbons and Geothermal Energy Office',
    year: 2026,
    url: 'https://www.energy.gov/hgeo/hgeo-workforce-programs',
    note: 'Official hub for MLEF, ORISE, Geothermal INTERN, GEODE, University Training and Research, PACT, and the Geothermal Collegiate Competition.',
  },
  {
    num: 30,
    id: 'nps-thpo-program',
    title: 'Tribal Historic Preservation Office Program',
    org: 'National Park Service · Historic Preservation Fund',
    year: 2025,
    url: 'https://www.nps.gov/subjects/historicpreservationfund/tribal-historic-preservation-office-program.htm',
    note: 'NPS program supporting Tribal THPO designation, Section 106 coordination, formula grants to THPOs, and competitive Tribal Heritage Grants.',
  },
  {
    num: 31,
    id: 'nathpo-thpo',
    title: 'What is a THPO?',
    org: 'National Association of Tribal Historic Preservation Officers (NATHPO)',
    year: null,
    url: 'https://www.nathpo.org/what-is-a-thpo/',
    note: 'Tribal designation under NHPA Section 101(d)(2), formal NPS preservation plans, traditional cultural properties, and THPO roles in federal undertaking review.',
  },
  {
    num: 32,
    id: 'project-innerspace',
    title: 'Project InnerSpace',
    org: 'Project InnerSpace',
    year: null,
    url: 'https://projectinnerspace.org',
    note: 'Philanthropy-funded nonprofit focused on exponential global geothermal growth by 2030. Publishes the open GeoMap prospecting platform, the GeoFund pilot program, PIVOT convenings, regional Future of Geothermal studies, and O&G-to-geothermal crossover work including GEODE consortium formation with SPE and Geothermal Rising.',
  },
  {
    num: 33,
    id: 'cem-geofuture',
    title: 'GeoFuture Initiative (Clean Energy Ministerial)',
    org: 'Clean Energy Ministerial',
    year: 2025,
    url: 'https://www.cleanenergyministerial.org/initiatives-campaigns/geofuture-initiative/',
    note: 'CEM initiative launched at CEM16 by the United States with Japan and Saudi Arabia to accelerate next-generation geothermal deployment. Coordinated by the National Laboratory of the Rockies. Focuses on investment advocacy, knowledge exchange and technical assistance, stakeholder convening, a next-generation geothermal case study series, and feasibility support for national energy planning.',
  },
  {
    num: 34,
    id: 'iea-future-geothermal',
    title: 'The Future of Geothermal Energy',
    org: 'International Energy Agency',
    year: 2024,
    url: 'https://www.iea.org/reports/the-future-of-geothermal-energy',
    note: 'Global outlook for next-generation geothermal technologies, cost trajectories, and policy gaps. Cited by the CEM GeoFuture Initiative for projections of up to 800 GW of installed next-generation geothermal capacity by 2050 under favorable conditions.',
  },
  {
    num: 35,
    id: 'api-rp-92m-mpd',
    title: 'Managed Pressure Drilling Operations (API RP 92M)',
    org: 'American Petroleum Institute / IADC WellSHARP',
    year: null,
    url: 'https://iadc.org/wp-content/uploads/2021/12/WSP-MPDOperationsMatrix-per-API-RP-92M.pdf',
    note: 'Industry reference for MPD operations matrices: operating, planned, and back-pressure limits; influx categorization; and transition from MPD mode to conventional well control. IADC publishes an example matrix aligned with API RP 92M.',
  },
  {
    num: 36,
    id: 'well-control-school-glossary',
    title: 'Well Control School Glossary',
    org: 'Well Control School (WCS)',
    year: null,
    url: 'https://wellcontrolschool.com/glossary',
    note: 'Alphabetized drilling and well control glossary with more than 1,300 defined terms, from kicks and BOPE to mud properties and rig equipment. Hosted at learnwellcontrol.com; WCS also delivers IADC WellCAP/WellSHARP and IWCF certification training in Houston, Lafayette, and Laurel.',
  },
  {
    num: 37,
    id: 'world-bank-geothermal-feasibility',
    title: 'Preparing Feasibility Studies for the Financing of Geothermal Projects',
    org: 'World Bank / ESMAP',
    year: 2012,
    url: 'https://documents.worldbank.org/en/publication/documents-reports/documentdetail/36016',
    note: 'Overview of best practices for geothermal feasibility studies across project phases. Describes how technical risk and cost uncertainty are highest during exploration and test drilling, then fall as the resource is confirmed and the field moves toward operation.',
  },
]

export const CITATIONS_PAGE = {
  kicker: 'Helpful links · References',
  titleLead: 'Sources',
  titleEmphasis: 'cited on this site',
  lede: 'Numbered references for statistics, regional data, and claims drawn from other organizations\u2019 work. Inline superscripts on site pages link here. External tool and portal cards on Helpful links point to the same sources where applicable.',
  intro: [
    'This site is a field guide, not a primary research archive. Where prose restates capacity figures, recovery rates, permitting timelines, or regional datasets, those lines carry citation numbers linking to the original publisher.',
    'Corrections and additions are welcome through the About section.',
  ],
}

export function getCitation(num) {
  return CITATIONS.find(c => c.num === num) || null
}

export function getCitationById(id) {
  return CITATIONS.find(c => c.id === id) || null
}

/** Parse "1", "1-3", "1,3,5", or "1–3" into sorted unique citation numbers. */
export function expandCitationSpec(spec) {
  const nums = new Set()
  for (const part of spec.split(',')) {
    const trimmed = part.trim()
    const rangeMatch = trimmed.match(/^(\d+)\s*[–-]\s*(\d+)$/)
    if (rangeMatch) {
      const start = Number(rangeMatch[1])
      const end = Number(rangeMatch[2])
      for (let n = Math.min(start, end); n <= Math.max(start, end); n += 1) nums.add(n)
    } else if (/^\d+$/.test(trimmed)) {
      nums.add(Number(trimmed))
    }
  }
  return [...nums].sort((a, b) => a - b)
}
