#!/usr/bin/env python3
"""Build work.json from the FY 2027 Collaborative WBS."""
import json
from pathlib import Path

STREAMS = [
    ("1.0", "Program operations", "Charter, membership, public site, and measurement."),
    ("2.0", "Federal geothermal capacity", "Handbooks, categorical exclusions, rulemaking analysis, and field training, with BLM as design partner."),
    ("3.0", "Permitting Support Team", "Host-agency placements. Signed host commitments are required."),
    ("4.0", "State geothermal capacity", "Navigation assistance, regulatory programs, partner-state selection, and staff training."),
    ("5.0", "Tribal geothermal capacity", "Participation support and convening. Coordination only. Consultation stays with the responsible agency."),
    ("6.0", "Intergovernmental Geothermal Accelerator", "Cohorts, peer learning, technical assistance, and exchange sessions for intergovernmental geothermal permitting, plus Energy Determinants of Health pathway work."),
    ("7.0", "Permitting Innovation Exchange", "Hackathons, shark tanks, and challenge events that put industry, government, and applicants on the same permitting problems."),
    ("8.0", "Training and technical assistance", "Curriculum, federal and Tribal cohorts, applicant readiness, and published templates."),
    ("9.0", "Evidence and diffusion", "Practitioner participation, lab synthesis, and translation into briefs and sessions."),
    ("10.0", "Applied permitting research", "Multi-perspective case studies at PNNL, interviews, and observed durations for the GPCP rule set."),
    ("11.0", "Fellowship support", "Applied Permitting Research Fellow and Energy Determinants Fellow."),
]

# id, stream, name, quarter, performer, depends, capability, milestone, basis
ROWS = [
    ("1.1", "1.0", "Charter and operating model", "Q1",
     "Intergovernmental fellow with Program", "", "Portfolio coherence",
     "Charter adopted covering purpose, membership, participation terms and the relationship to GPCP, SEPI and existing lab research.",
     "Fellowship line and Program"),
    ("1.2", "1.0", "Membership map and convening cadence", "Q1",
     "Intergovernmental fellow", "1.1", "Portfolio coherence",
     "Participating federal, state, Tribal and applicant organizations identified, with the recurring cadence attached to the existing Nevada monthly interagency call.",
     "Fellowship line"),
    ("1.3", "1.0", "Digital presence and materials", "Q1–Q2",
     "Contractor", "1.1", "Portfolio coherence",
     "Public-facing site, session materials and a shared workspace for participants, Section 508 conformant.",
     "Contracted: build and content"),
    ("1.4", "1.0", "Participation and outcome measurement", "Q3–Q4",
     "Contractor with Systems fellow", "6.1, 7.2, 8.2", "Portfolio evidence",
     "Participation, backlog contribution, cohort completion and technical assistance reach measured, each traced to the capability it advances.",
     "Contracted: instrumentation"),
    ("2.1", "2.0", "Environmental review and categorical exclusion substantiation", "Q1–Q4",
     "NLR", "1.1", "Federal capacity",
     "Substantiation analysis supporting proposed categorical exclusions for geothermal activities, prepared to the standard a Federal Register notice requires, scoped with BLM as design partner and accepted by BLM as usable in a proposal it decides whether to make.",
     "Contracted: NLR"),
    ("2.2", "2.0", "Geothermal handbook development", "Q1–Q4",
     "NLR", "1.1", "Federal capacity",
     "Draft handbooks for geothermal leasing, exploration, well field development, utilization and unitization brought to final form against requirements set by BLM as design partner, accepted by BLM for adoption, published, and reusable in state model framework work at 4.2.",
     "Contracted: NLR"),
    ("2.3", "2.0", "Rulemaking technical analysis", "Q2–Q4",
     "NLR", "2.2", "Federal capacity",
     "Technical analysis and options on administrative burden and clarity in updated geothermal regulations, responding to questions BLM poses as design partner. Analysis and options; BLM drafts regulatory text.",
     "Contracted: NLR"),
    ("2.4", "2.0", "Training module updates", "Q2–Q4",
     "NLR", "2.2", "Federal capacity",
     "Existing geothermal leasing, exploration, well field development and utilization training modules updated to align with the final handbooks, accepted by BLM as design partner for use with its field staff, and published as open modules usable by state regulators and the training cohorts at 8.2.",
     "Contracted: NLR"),
    ("3.1", "3.0", "Team design and appointment vehicles", "Q2–Q3",
     "Intergovernmental fellow with Program, OGC and HR", "1.1", "Federal capacity",
     "Team model settled: which partner agencies host, what fellows and scholars do while placed there, which appointment vehicle applies to each role, what the host agency provides, and draft position descriptions.",
     "Fellowship line and Program"),
    ("3.2", "3.0", "Host agency commitments", "Q3–Q4",
     "Intergovernmental fellow with Program", "3.1", "Federal capacity",
     "Written commitments from host agencies covering placement, supervision, workspace and return arrangements. Signed host commitments are required.",
     "Fellowship line and Program"),
    ("3.3", "3.0", "Year 2 rollout plan", "Q4",
     "Intergovernmental fellow with Program", "3.2", "Federal capacity",
     "Cohort size, recruitment timeline, placement sequence and a costed Year 2 rollout.",
     "Fellowship line and Program"),
    ("4.1", "4.0", "Federal permitting navigation assistance", "Q2–Q4",
     "NLR, LBNL and PNNL with NASEO, Intergovernmental fellow coordinates", "1.1", "State capacity",
     "Existing federal products delivered and translated for states: RAPID, PermitAI and NEPATEC, LBNL timelines work and GPCP. Completes the federal portions of state permitting roadmaps for requesting states.",
     "Contracted: technical assistance"),
    ("4.2", "4.0", "State regulatory program and policy development", "Q2–Q4",
     "NASEO and NLR with OG state partnership lead", "4.3", "State regulatory capacity",
     "Direct support to states standing up or adapting geothermal regulatory programs, including model regulatory frameworks, ownership and regulatory alignment analysis, lead regulatory agency designation, and the UIC Class V primacy pathway with the Groundwater Protection Council.",
     "Contracted: regulatory analysis"),
    ("4.3", "4.0", "State convening, participation and partner state selection", "Q2–Q3",
     "NASEO with OG state partnership lead", "1.1", "State capacity",
     "Convening of states with geothermal potential delivered, with travel and participation costs covered for state staff across all Collaborative sessions. Acceptance is a shortlist of partner states that have secured Governor-level commitment to advance geothermal through policy, permitting, procurement and partnership, following the NASEO first movers model.",
     "Contracted: convening, travel and participation"),
    ("4.4", "4.0", "State-specific technical analyses", "Q3–Q4",
     "National laboratories with NASEO", "4.3", "State capacity",
     "Analyses scoped to what a partner state will act on: novel technology evaluation, interconnection, surface and water resource protection including thermal features, and incentive design.",
     "Contracted: analysis"),
    ("4.5", "4.0", "State regulatory staff training", "Q3–Q4",
     "Training provider, Intergovernmental fellow recruits", "4.1, 8.1", "State capacity",
     "Federal permitting and regulatory training delivered to state regulatory and energy office staff, reusing the Collaborative curriculum.",
     "Contracted: instruction and materials"),
    ("5.1", "5.0", "Tribal participation support", "Q1–Q4",
     "Contractor, Intergovernmental fellow coordinates", "1.2", "Tribal capacity",
     "Travel and participation costs covered for Tribal environmental and cultural staff. Coordination only. Consultation authority remains with the responsible federal agency.",
     "Contracted: participation support"),
    ("5.2", "5.0", "Tribal Government convening", "Q2–Q4",
     "Contractor with Intergovernmental fellow and Office of Indian Energy", "1.2", "Tribal capacity",
     "Two sessions co-designed with participating Tribal Governments and Tribal organizations around their stated geothermal and permitting priorities, held alongside existing venues such as the Indian Country Energy and Infrastructure Working Group or BIA regional Federal Partners meetings. Coordination only. Consultation stays with the responsible federal agency.",
     "Contracted: convening and travel"),
    ("6.1", "6.0", "Recurring permitting exchange sessions", "Q1–Q4",
     "Contractor, Intergovernmental fellow convenes", "1.2", "Agency participation",
     "At least eight sessions held with documented participation from BLM, one state agency and one Tribal-facing office.",
     "Contracted: facilitation and platform"),
    ("6.2", "6.0", "Annual in-person exchange", "Q3",
     "Contractor, Intergovernmental fellow convenes", "6.1", "Agency participation",
     "One multi-day exchange delivered, bringing federal, state, Tribal and applicant participants into the same room.",
     "Contracted: venue and logistics"),
    ("6.3", "6.0", "Regional sessions", "Q2, Q4",
     "Contractor, Intergovernmental fellow convenes", "6.1", "Agency participation",
     "Two regional sessions held in geothermal-active states, at least one hosted by a BLM state or district office.",
     "Contracted: venue and travel"),
    ("6.4", "6.0", "Local and non-federal participation support", "Q1–Q4",
     "Contractor, Intergovernmental fellow coordinates", "1.2", "Agency participation",
     "Travel and participation costs covered for local government, applicant and other non-federal participants whose organizations cannot fund attendance. State participation sits in 4.3 and Tribal participation in 5.1.",
     "Contracted: participation support"),
    ("6.5", "6.0", "Energy determinants pathway map and indicator inventory", "Q1–Q3",
     "Energy Determinants fellow", "1.2", "Portfolio evidence",
     "Four pathways characterized under one structure: affordability and thermal conditions, reliability for medically vulnerable populations, exposures from production and heating technologies, and energy-sector employment and occupational conditions. Each entry names the energy condition, the affected population or workforce, the downstream mechanism, an existing indicator held by another agency, and whether the link is established or plausible and unverified. Pathways ranked by evidentiary maturity.",
     "Fellowship line"),
    ("6.6", "6.0", "Energy determinants interagency working group", "Q2–Q4",
     "Contractor, Energy Determinants fellow convenes", "6.5", "Agency participation",
     "At least six sessions with documented participation from HHS, the Indian Health Service, VA and DOL. Each session tests one pathway entry against the agency holding the indicator and produces either confirmation that the measure can be used as identified or a statement of what would be required. No pathway advances to Year 2 on the fellow's characterization alone.",
     "Contracted: platform and logistics"),
    ("6.7", "6.0", "Energy determinants convening", "Q3",
     "Contractor, Energy Determinants fellow convenes", "6.6", "Agency participation",
     "One convening with community, Tribal, health-agency and workforce participation, structured around the ranked pathways, with travel support for participants whose organizations cannot fund attendance.",
     "Contracted: venue, travel, logistics"),
    ("7.1", "7.0", "Challenge development and problem statements", "Q1–Q2",
     "Contractor with Systems fellow", "1.1", "GPCP requirements",
     "Problem statements drawn from GPCP requirements and the pilot backlog, with judging criteria and data access arrangements settled.",
     "Contracted: platform and design"),
    ("7.2", "7.0", "Three hackathon events", "Q2, Q3, Q4",
     "Contractor, Systems fellow directs", "7.1", "GPCP adoption",
     "Three events delivered, with participation from outside DOE, including at least one non-federal team and one event co-hosted with a state agency.",
     "Contracted: venue, platform, travel"),
    ("7.3", "7.0", "Output triage and technical assessment", "Q2–Q4",
     "Systems fellow with NLR", "7.2", "GPCP requirements",
     "Every output assessed and dispositioned. Prototypes enter the backlog as candidate requirements.",
     "Contracted: NLR sizing"),
    ("8.1", "8.0", "Curriculum development", "Q1–Q2",
     "Training provider with Systems fellow", "1.1", "Federal capacity",
     "Curriculum covering permitting project management and applied AI for permitting staff, reviewed by practitioners.",
     "Contracted: curriculum development"),
    ("8.2", "8.0", "Federal and Tribal training cohorts", "Q2–Q4",
     "Training provider, Intergovernmental fellow recruits", "8.1", "GPCP adoption",
     "Cohorts completed for federal permitting staff and for Tribal environmental offices. Graduates form the recruitment pool for GPCP pilot onboarding.",
     "Contracted: instruction and materials"),
    ("8.3", "8.0", "Applicant pre-application readiness support", "Q2–Q4",
     "Contractor with Systems fellow", "1.1", "Process improvement",
     "Direct assistance to at least eight project proponents, prioritizing developers without in-house permitting counsel. Assistance is readiness support.",
     "Contracted: subject matter support"),
    ("8.4", "8.0", "Permitting guidance materials and templates", "Q2–Q4",
     "Contractor with Systems fellow", "8.3", "Process improvement",
     "Checklists, submission templates and process guidance published, cross-referenced to RAPID and BLM guidance.",
     "Contracted: content development"),
    ("9.1", "9.0", "Practitioner participation in applied research", "Q2–Q4",
     "Contractor with Applied Permitting Research fellow", "1.2", "Process improvement",
     "Collaborative membership supplies the sampling frame for the applied research program. Practitioners identified, recruited and scheduled for interviews and case reconstruction, with at least two sessions in which practitioners react to draft findings before they are finalized.",
     "Contracted: recruitment and session support"),
    ("9.2", "9.0", "Evidence synthesis from lab research", "Q2–Q4",
     "Contractor with Applied Permitting Research fellow", "9.1", "GPCP requirements",
     "Findings from LBNL timelines and PNNL applied permitting research synthesized into a form usable by the GPCP dependency rule set and instrumentation.",
     "Contracted: analyst support"),
    ("9.3", "9.0", "Applied research translation and diffusion", "Q2–Q4",
     "Contractor with Applied Permitting Research fellow", "9.1", "Subsurface extension",
     "Case research turned into practitioner briefs, training cases and cross-domain lessons, and worked into Collaborative sessions.",
     "Contracted: translation"),
    ("10.1", "10.0", "Case selection, methods and records", "Q1–Q2",
     "PNNL with Applied Permitting Research fellow", "9.1", "Process improvement",
     "Case selection logic, common case structure, protocols and records assembled, with the Paperwork Reduction Act question resolved before any non-federal respondent is approached.",
     "PNNL annual operating plan"),
    ("10.2", "10.0", "Four to six multi-perspective case studies", "Q2–Q4",
     "PNNL", "10.1", "Process improvement",
     "Each case reconstructs the project chronology from initial development activity through agency reviews and decisions, across applicant, BLM, state, wildlife, cultural resource, Tribal-facing and cooperating agency perspectives. One or two cases carry the existing surface thermal features work.",
     "PNNL annual operating plan"),
    ("10.3", "10.0", "Permitting official and applicant interviews and field visits", "Q2–Q4",
     "PNNL with Applied Permitting Research fellow", "10.1", "Process improvement",
     "What information was requested and when it became available, where handoffs occurred, what caused rework or waiting, which dependencies were understood in advance, and where written process differed from actual practice.",
     "PNNL annual operating plan"),
    ("10.4", "10.0", "Cross-case comparative analysis", "Q3–Q4",
     "PNNL with Permitting Outcomes fellow", "10.2, 10.3", "GPCP requirements",
     "Recurring patterns identified across cases, with observed durations that replace stated assumptions in the GPCP rule set.",
     "PNNL annual operating plan"),
    ("10.5", "10.0", "Evidence products and research meeting", "Q3–Q4",
     "PNNL, Applied Permitting Research fellow convenes", "10.4", "GPCP requirements",
     "Findings delivered in a form GPCP requirements, the SEPI data model, curriculum and state technical assistance can use. Includes venue, materials and participant travel for the annual OG permitting research meeting; agenda and synthesis are fellow work.",
     "PNNL annual operating plan"),
    ("11.1", "11.0", "Applied Permitting Research Fellow", "Q1–Q4",
     "Fellowship appointment", "", "Process improvement",
     "Research agenda, case selection, practitioner interviews, cross-lab inventory and the annual research meeting, transfer of findings into requirements.",
     "Fellowship appointment"),
    ("11.2", "11.0", "Energy Determinants Fellow", "Q1–Q4",
     "Fellowship appointment", "", "Portfolio evidence",
     "Energy affordability and thermal conditions, reliability for medically vulnerable populations, exposures from production and heating technologies, and energy-sector employment and occupational conditions. Workforce is treated as a mediated pathway.",
     "Fellowship appointment"),
]


def main():
    stream_by_id = {sid: {"id": sid, "name": name, "note": note} for sid, name, note in STREAMS}
    packages = []
    for row in ROWS:
        pid, stream, name, quarter, performer, depends, capability, milestone, basis = row
        packages.append({
            "id": pid,
            "stream": stream,
            "stream_name": stream_by_id[stream]["name"],
            "name": name,
            "quarter": quarter,
            "performer": performer,
            "depends": depends,
            "capability": capability,
            "milestone": milestone,
            "basis": basis,
        })
    data = {
        "updated": "2026-08-27",
        "source": "GPIC",
        "url": "https://gpic.thermalunderground.org/work.json",
        "inventory": "Year 1 WBS. Geothermal Permitting Innovation Collaborative sheet of the Proposed Permitting Funding Request FY27.",
        "streams": list(stream_by_id.values()),
        "packages": packages,
    }
    out = Path(__file__).resolve().parent.parent / "work.json"
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {len(packages)} packages, {len(STREAMS)} streams -> {out}")


if __name__ == "__main__":
    main()
