#!/usr/bin/env python3
"""Build connectors.json from the 21 Aug 2026 inventory spreadsheet."""
import json
from pathlib import Path

# status: go = VERIFIED WORKING, hold = BROKEN/MOVED, syn = NO PUBLIC SURFACE/API, open = not probed
# method only when the inventory names how the read was made. Blank is shown as —.
ROWS = [
    # group, id, name, owner, holds, tier, applies, priority, light, status, endpoint, url, method
    ("BLM", "mlrs", "MLRS geothermal leases", "BLM",
     "Lease polygons, case serial, disposition, acreage, production status, dates",
     "sepi", "Every federal geothermal project", 1, "go", "VERIFIED WORKING",
     "BLM MLRS geothermal leases FeatureServer", "https://gis.blm.gov/nlsdb/rest/services/HUB/BLM_Natl_MLRS_Geothermal_Leases/FeatureServer/0", "gis"),
    ("BLM", "mlrs-case", "MLRS case management", "BLM",
     "Case lifecycle, adjudication, intake workflow",
     "sepi", "Any case action after lease issuance", 1, "syn", "NO PUBLIC SURFACE",
     "Behind DOI network and ICAM", "", ""),
    ("BLM", "afmss", "AFMSS / AFMSSv2", "BLM",
     "Drilling permits, well operations, inspections",
     "sepi", "Any drilling", 1, "syn", "NO PUBLIC SURFACE",
     "Behind DOI network", "", ""),
    ("BLM", "eplanning", "ePlanning", "BLM",
     "NEPA project records, documents, decisions",
     "sepi", "Every federal action requiring NEPA", 1, "syn", "NO PUBLIC API",
     "OData disabled; document search only", "https://eplanning.blm.gov/", ""),
    ("BLM", "nlcs-monuments", "NLCS National Monuments and NCAs", "BLM",
     "Designated monument and conservation area boundaries",
     "sepi", "Land status gating authorization", 1, "go", "VERIFIED WORKING",
     "BLM NLCS geospatial service", "https://gis.blm.gov/", "gis"),
    ("BLM", "nlcs-wsa", "NLCS Wilderness Study Areas", "BLM",
     "WSA boundaries",
     "sepi", "Land status gating authorization", 1, "go", "VERIFIED WORKING",
     "BLM NLCS geospatial service", "https://gis.blm.gov/", "gis"),
    ("BLM", "nlcs-wilderness", "NLCS Wilderness Areas", "BLM",
     "Designated wilderness boundaries",
     "sepi", "Land status gating authorization", 1, "go", "VERIFIED WORKING",
     "BLM NLCS geospatial service", "https://gis.blm.gov/", "gis"),
    ("BLM", "acec", "Areas of Critical Environmental Concern", "BLM",
     "ACEC boundaries and designations",
     "sepi", "Land status gating authorization", 2, "go", "VERIFIED WORKING",
     "BLM geospatial service", "https://gis.blm.gov/", "gis"),
    ("BLM", "sma-withdrawals", "Natl SMA Withdrawals", "BLM",
     "Land withdrawn from disposition",
     "sepi", "Land status gating authorization", 1, "hold", "BROKEN / MOVED",
     "Host returns 500", "", ""),
    ("BLM", "rmp", "Resource Management Plans", "BLM",
     "Approved land use plans",
     "both", "Plan conformance", 1, "go", "VERIFIED WORKING",
     "BLM land use plan geospatial service", "https://gis.blm.gov/", "gis"),
    ("BLM", "lr2000", "LR2000", "BLM",
     "Legacy land and mineral case records",
     "sepi", "Historic case chains", 3, "open", "",
     "", "", ""),
    ("BLM", "navigator", "Navigator / GeoCommunicator", "BLM",
     "Surface and mineral estate status",
     "sepi", "Split estate screening", 2, "open", "",
     "", "", ""),
    ("BLM", "niis", "NIIS", "BLM",
     "Cadastral survey and boundary data",
     "nexus", "Parcel resolution", 3, "open", "",
     "", "", ""),
    ("BLM", "nflss", "NFLSS", "BLM",
     "Scope unconfirmed. Named in July 2026 meeting notes.",
     "sepi", "", 3, "open", "",
     "", "", ""),

    ("Forest Service", "pals", "PALS", "USFS",
     "NEPA project status and decisions",
     "sepi", "Geothermal on National Forest System lands", 1, "open", "",
     "", "", ""),
    ("Forest Service", "sopa", "SOPA", "USFS",
     "Schedule of proposed actions",
     "sepi", "Forward pipeline visibility", 2, "open", "",
     "", "", ""),
    ("Forest Service", "nrm-suds", "NRM SUDS", "USFS",
     "Special use authorizations",
     "sepi", "Surface use on NFS lands", 2, "open", "",
     "", "", ""),
    ("Forest Service", "nrm-infra", "NRM INFRA", "USFS",
     "Infrastructure and facilities records",
     "sepi", "Roads, buildings, utilities on NFS lands", 3, "open", "",
     "", "", ""),
    ("Forest Service", "facts", "FACTS", "USFS",
     "Activity and treatment records",
     "nexus", "Vegetation and fuels context", 3, "open", "",
     "", "", ""),
    ("Forest Service", "usfs-consent", "USFS consent decisions", "USFS",
     "Consent to BLM geothermal leasing on NFS lands",
     "sepi", "Any geothermal lease on NFS lands", 1, "open", "",
     "", "", ""),
    ("Forest Service", "nfs-boundaries", "National Forest boundaries", "USFS",
     "Administrative unit boundaries",
     "nexus", "Jurisdiction determination", 2, "open", "",
     "", "", ""),

    ("Army Corps", "orm2", "ORM2 / RRS", "USACE",
     "CWA Section 404 permits, individual and nationwide",
     "sepi", "Discharge into waters of the US", 1, "open", "",
     "", "", ""),
    ("Army Corps", "usace-jd", "Jurisdictional determinations", "USACE",
     "Approved and preliminary JDs",
     "sepi", "A negative JD removes the entire 404 track", 1, "open", "",
     "", "", ""),
    ("Army Corps", "usace-notices", "District public notices", "USACE",
     "Pending applications",
     "sepi", "Visibility into pending work", 3, "open", "",
     "", "", ""),
    ("Army Corps", "usace-districts", "USACE districts and wetland regions", "USACE",
     "Administrative boundaries",
     "nexus", "Which district has jurisdiction", 2, "go", "VERIFIED WORKING",
     "Via PNNL nepa-map usace server", "", "gis"),
    ("Army Corps", "nwpl", "National Wetland Plant List", "USACE",
     "Species indicator status",
     "nexus", "Wetland delineation reference", 3, "open", "",
     "", "", ""),

    ("NOAA Fisheries", "pcts", "PCTS", "NOAA NMFS",
     "Section 7 consultation tracking, marine",
     "sepi", "Anadromous or marine species present", 2, "open", "",
     "", "", ""),
    ("NOAA Fisheries", "mmpa", "MMPA incidental take", "NOAA NMFS",
     "IHAs and Letters of Authorization",
     "sepi", "Marine mammals present, Hawaii, coastal", 3, "open", "",
     "", "", ""),
    ("NOAA Fisheries", "efh-consult", "EFH consultation records", "NOAA NMFS",
     "Essential Fish Habitat consultations",
     "sepi", "EFH present", 3, "open", "",
     "", "", ""),
    ("NOAA Fisheries", "efh-hapc", "EFH and HAPC areas", "NOAA NMFS",
     "Habitat boundaries",
     "nexus", "Screening", 2, "go", "VERIFIED WORKING",
     "Via PNNL nepa-mcp efh server", "", "mcp"),
    ("NOAA Fisheries", "esa-marine", "ESA species ranges, marine", "NOAA NMFS",
     "Listed species ranges",
     "nexus", "Screening", 2, "go", "VERIFIED WORKING",
     "Via PNNL nepa-mcp esa_ranges server", "", "mcp"),
    ("NOAA Fisheries", "ncei", "NCEI bathymetry and geophysics", "NOAA",
     "Seafloor, gravity, magnetics, seismic",
     "nexus", "Offshore or coastal characterization", 3, "open", "",
     "", "", ""),
    ("NOAA Fisheries", "thermal-springs", "Thermal Springs of the United States", "NOAA NGDC",
     "Historic thermal spring inventory",
     "nexus", "Resource context", 3, "open", "",
     "", "", ""),

    ("Coast Guard", "bridge-permits", "Bridge permits", "USCG",
     "Bridge and causeway authorizations over navigable waters",
     "sepi", "Transmission or road crossing navigable water", 3, "open", "",
     "", "", ""),
    ("Coast Guard", "lnm", "Local Notice to Mariners", "USCG",
     "Marine construction notices",
     "sepi", "In-water work", 3, "open", "",
     "", "", ""),
    ("Coast Guard", "misle", "MISLE", "USCG",
     "Marine incident, inspection, and enforcement",
     "nexus", "Compliance history", 3, "open", "",
     "", "", ""),

    ("Tribal", "taams", "BIA TAAMS", "BIA",
     "Trust asset and lease records",
     "sepi", "Trust or restricted land involved", 2, "open", "",
     "", "", ""),
    ("Tribal", "thpo", "THPO systems", "Tribes",
     "Section 106 review status",
     "sepi", "Federal undertaking on tribal land", 2, "open", "",
     "", "", ""),
    ("Tribal", "tribal-env", "Tribal environmental programs", "Tribes",
     "TAS status and water quality standards",
     "sepi", "Treatment-as-state water quality", 3, "open", "",
     "", "", ""),
    ("Tribal", "tero", "Tribal Employment Rights Offices", "Tribes",
     "TERO requirements and fees",
     "sepi", "Work on tribal land", 3, "open", "",
     "", "", ""),
    ("Tribal", "nagpra", "NAGPRA notices", "NPS / Federal Register",
     "Inventory and repatriation notices",
     "nexus", "Consultation scoping", 3, "go", "VERIFIED WORKING",
     "Federal Register API", "https://www.federalregister.gov/api/v1/documents.json", ""),
    ("Tribal", "tiger", "TIGERweb AIANHA", "Census",
     "Reservation and trust land boundaries",
     "nexus", "Consultation range and jurisdiction", 1, "go", "VERIFIED WORKING",
     "TIGERweb AIANNH MapServer, layers 2 and 3", "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/AIANNH/MapServer", "gis"),
    ("Tribal", "tribal-consult", "Tribal consultation status", "BLM / Tribes",
     "Consultation timing and records",
     "sepi", "Any federal undertaking with tribal interest", 1, "open", "",
     "", "", ""),

    ("Consultation Cultural", "ipac", "IPaC Location API", "USFWS",
     "Species, critical habitat, wetlands, field office",
     "nexus", "Every project. Determines Section 7 trigger", 1, "go", "VERIFIED WORKING",
     "POST IPaC Location API", "https://ipac.ecosphere.fws.gov/location/api/resources", "mcp"),
    ("Consultation Cultural", "tails", "TAILS", "USFWS",
     "Section 7 consultation tracking and completion",
     "sepi", "Listed species present", 1, "open", "",
     "", "", ""),
    ("Consultation Cultural", "ecos", "ECOS", "USFWS",
     "Species listings, critical habitat, recovery plans",
     "nexus", "Screening", 2, "open", "",
     "", "", ""),
    ("Consultation Cultural", "e106", "e106", "ACHP",
     "Section 106 notices and submissions",
     "sepi", "Federal undertaking", 2, "open", "",
     "", "", ""),
    ("Consultation Cultural", "nrhp", "NRHP", "NPS",
     "Listed and eligible historic properties",
     "nexus", "Federal undertaking", 2, "go", "VERIFIED WORKING",
     "Via PNNL nepa-map nrhp server", "", "gis"),
    ("Consultation Cultural", "shpo", "SHPO systems", "States",
     "Section 106 review status",
     "sepi", "Federal undertaking", 2, "open", "",
     "", "", ""),
    ("Consultation Cultural", "pepc", "PEPC", "NPS",
     "Planning, environment, and public comment",
     "sepi", "Adjacent park units", 3, "open", "",
     "", "", ""),
    ("Consultation Cultural", "gsa-thermal", "Geothermal Steam Act thermal features", "NPS",
     "Protected thermal features and BLM coordination",
     "sepi", "Development that could impair park thermal systems", 2, "open", "",
     "", "", ""),

    ("Water Air Waste", "uic", "SDWIS / UIC", "EPA",
     "Class V injection well permits",
     "sepi", "Any injection", 1, "open", "",
     "", "https://www.epa.gov/uic", ""),
    ("Water Air Waste", "echo", "ICIS / ECHO", "EPA",
     "Compliance and enforcement",
     "nexus", "Compliance history", 2, "open", "",
     "", "", ""),
    ("Water Air Waste", "title-v", "Title V air permits", "EPA / delegated state",
     "Major source air permits",
     "sepi", "Major air source", 2, "open", "",
     "", "", ""),
    ("Water Air Waste", "npdes", "NPDES", "EPA / delegated state",
     "Discharge permits",
     "sepi", "Discharge to waters", 1, "open", "",
     "", "", ""),
    ("Water Air Waste", "rcra", "RCRA", "EPA / delegated state",
     "Hazardous waste",
     "sepi", "Waste handling", 2, "open", "",
     "", "", ""),
    ("Water Air Waste", "nepassist", "NEPAssist", "EPA",
     "Screening layers",
     "nexus", "Early screening", 2, "go", "VERIFIED WORKING",
     "Via PNNL nepa-map", "", "gis"),
    ("Water Air Waste", "envirofacts", "Envirofacts", "EPA",
     "Cross-program facility and permit data",
     "both", "Facility resolution", 2, "open", "",
     "", "", ""),
    ("Water Air Waste", "nwi", "NWI Wetlands", "FWS via USGS",
     "Wetland polygons",
     "nexus", "Screening", 1, "go", "VERIFIED WORKING",
     "FWS National Wetlands Inventory MapServer", "https://www.fws.gov/program/national-wetlands-inventory", "gis"),
    ("Water Air Waste", "nhd", "NHD", "USGS",
     "Hydrography",
     "nexus", "Screening", 1, "go", "VERIFIED WORKING",
     "nationalmap.gov MapServer", "https://www.usgs.gov/national-hydrography/national-hydrography-dataset", "gis"),
    ("Water Air Waste", "nfhl", "FEMA NFHL", "FEMA",
     "Flood zones and levees",
     "nexus", "Early screening", 2, "go", "VERIFIED WORKING",
     "Via PNNL nepa-map", "", "gis"),
    ("Water Air Waste", "ndwr", "Nevada Division of Water Resources", "Nevada",
     "Water rights and well logs",
     "sepi", "Nevada water use", 1, "hold", "BROKEN / MOVED",
     "gis.water.nv.gov does not resolve", "https://water.nv.gov/", ""),

    ("Other Federal", "faa-oeaaa", "OE/AAA", "FAA",
     "Obstruction evaluation and airspace review",
     "sepi", "Structures over 200 feet, transmission", 3, "open", "",
     "", "", ""),
    ("Other Federal", "ferc", "eLibrary / eTariff", "FERC",
     "Interconnection and transmission filings",
     "sepi", "Grid interconnection", 2, "open", "",
     "", "", ""),
    ("Other Federal", "dod-ranges", "Military installation and range boundaries", "DOD",
     "Installation, range, and target area boundaries",
     "sepi", "Proximity to military land", 1, "go", "VERIFIED WORKING",
     "Returned via PAD-US Combined", "https://www.usgs.gov/programs/gap-analysis-project/science/pad-us-data-overview", "gis"),
    ("Other Federal", "bor", "Reclamation land and water contracts", "BOR",
     "Land use authorizations, water service contracts",
     "sepi", "Reclamation project lands or water", 3, "open", "",
     "", "", ""),
    ("Other Federal", "phmsa", "PHMSA", "DOT",
     "Pipeline safety and operator records",
     "sepi", "Gathering or transmission pipelines", 3, "open", "",
     "", "", ""),
    ("Other Federal", "msha", "MSHA mine registration", "DOL",
     "Mine ID and registration",
     "sepi", "Where geothermal touches mining claims", 3, "open", "",
     "", "", ""),
    ("Other Federal", "fast41", "Permitting Dashboard", "FPISC",
     "FAST-41 schedules and milestones",
     "sepi", "Covered projects only", 1, "open", "",
     "permits.performance.gov", "https://permits.performance.gov", ""),
    ("Other Federal", "sam", "SAM.gov", "GSA",
     "Entity registration",
     "nexus", "Applicant entity resolution", 3, "open", "",
     "", "https://sam.gov/", ""),
    ("Other Federal", "local-permits", "State fire marshal, county building and grading", "States, counties",
     "Local construction and use permits",
     "sepi", "Nearly every project", 2, "open", "",
     "", "", ""),

    ("Reference Knowledge", "rapid", "OpenEI RAPID Toolkit", "DOE / NLR",
     "Regulatory and permitting references",
     "nexus", "Permitting narratives", 1, "go", "VERIFIED WORKING",
     "openei.org wiki API", "https://openei.org/wiki/RAPID/Geothermal", "extract"),
    ("Reference Knowledge", "gem", "Geospatial Energy Mapper", "ANL",
     "Energy facility siting and constraint layers for early spatial screening",
     "nexus", "Applicant siting and constraint screening", 1, "open", "",
     "Public web map at gem.anl.gov", "https://gem.anl.gov/", ""),
    ("Reference Knowledge", "tethys", "Tethys environmental effects hub", "PNNL",
     "Literature and knowledge records on environmental effects of wind and marine energy",
     "nexus", "Transferable environmental-effects literature", 2, "open", "",
     "Public knowledge hub at tethys.pnnl.gov", "https://tethys.pnnl.gov/", ""),
    ("Reference Knowledge", "pic-standards", "NEPA and Permitting Data Standard", "GSA PIC",
     "Government-wide schema",
     "nexus", "Record shape", 2, "go", "VERIFIED WORKING",
     "github.com/GSA-TTS/pic-standards", "https://github.com/GSA-TTS/pic-standards", "extract"),
    ("Reference Knowledge", "nepa-mcp", "PNNL NEPA MCP Toolkit", "PNNL",
     "19 servers and 32 GIS layers",
     "nexus", "Screening stack", 1, "go", "VERIFIED WORKING",
     "pip install nepa-mcp", "", "mcp"),
    ("Reference Knowledge", "permitai", "NEPATEC 2.0", "PNNL",
     "NEPA project corpus",
     "nexus", "Document corpus", 1, "go", "VERIFIED WORKING",
     "Hugging Face PNNL/NEPATEC2.0", "https://huggingface.co/datasets/PNNL/NEPATEC2.0", "extract"),
    ("Reference Knowledge", "gdr", "GDR", "DOE OG",
     "Geothermal datasets",
     "nexus", "Resource context", 2, "open", "",
     "Nexus data layer", "", ""),
    ("Reference Knowledge", "ogrre", "OGRRE", "DOE",
     "Digitized oil and gas well records from scanned regulatory files: location, construction, status",
     "nexus", "Historic well construction", 2, "go", "VERIFIED WORKING",
     "catalog.energy.gov CATALOG OGRRE", "https://catalog.energy.gov/portfolio-items/catalog-data-extraction/", "extract"),
    ("Reference Knowledge", "dep", "3DEP Elevation", "USGS",
     "Bare earth DEM, hillshade, slope",
     "nexus", "Terrain", 2, "go", "VERIFIED WORKING",
     "elevation.nationalmap.gov ImageServer", "https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer", "gis"),
    ("Reference Knowledge", "datagov", "data.gov CKAN", "GSA",
     "Cross-agency dataset metadata",
     "nexus", "Catalog", 3, "hold", "BROKEN / MOVED",
     "catalog.data.gov/api/3", "https://catalog.data.gov/", ""),

    ("States", "ndom", "NV Division of Minerals", "Nevada",
     "Well permits",
     "sepi", "Nevada is a dual permit state", 1, "open", "",
     "", "https://minerals.nv.gov/", ""),
    ("States", "ndep", "NDEP", "Nevada",
     "State environmental permits",
     "sepi", "Nevada water pollution and UIC", 1, "open", "",
     "", "https://ndep.nv.gov/", ""),
    ("States", "nv-shpo", "NV SHPO", "Nevada",
     "State historic preservation review",
     "sepi", "Federal undertaking in Nevada", 2, "open", "",
     "", "https://shpo.nv.gov/", ""),
    ("States", "nv-lands", "NV State Lands", "Nevada",
     "State land authorizations",
     "sepi", "State land involved", 2, "open", "",
     "", "", ""),
    ("States", "nv-counties", "NV counties (Churchill, Pershing, Elko)", "Nevada counties",
     "Local land use and construction permits",
     "sepi", "Nearly every Nevada project", 2, "open", "",
     "", "", ""),
    ("States", "utah-dogm", "Utah DOGM", "Utah",
     "Oil, gas, and mining permits",
     "sepi", "Phase 5 portability", 2, "open", "",
     "", "", ""),
    ("States", "calgem", "CalGEM WellSTAR", "California",
     "Well records",
     "sepi", "Phase 5 portability", 2, "open", "",
     "", "", ""),
    ("States", "ceqanet", "CEQAnet", "California",
     "State environmental review documents",
     "sepi", "California environmental review", 2, "open", "",
     "", "", ""),
    ("States", "idaho-dwr", "Idaho DWR", "Idaho",
     "Water rights",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),
    ("States", "dogami", "Oregon DOGAMI", "Oregon",
     "Geologic and mineral permits",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),
    ("States", "hawaii-dlnr", "Hawaii DLNR", "Hawaii",
     "Land and resource authorizations",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),
    ("States", "nm-ocd", "New Mexico OCD", "New Mexico",
     "Oil conservation well records",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),
    ("States", "co-ecmc", "Colorado ECMC", "Colorado",
     "Energy and carbon management well records",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),
    ("States", "tx-rrc", "Texas RRC", "Texas",
     "Oil and gas well records",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),
    ("States", "ak-aogcc", "Alaska AOGCC", "Alaska",
     "Oil and gas conservation records",
     "sepi", "Phase 5 portability", 3, "open", "",
     "", "", ""),

    ("Identity and Access", "login-gov", "Login.gov", "GSA",
     "Public identity",
     "access", "Public users", 1, "open", "",
     "", "https://login.gov/", ""),
    ("Identity and Access", "piv-cac", "PIV / CAC", "All agencies",
     "Federal smart-card identity",
     "access", "Federal staff", 1, "open", "",
     "", "", ""),
    ("Identity and Access", "doe-icam", "DOE ICAM", "DOE",
     "DOE identity and credentialing",
     "access", "DOE network resources", 1, "open", "",
     "", "", ""),
    ("Identity and Access", "doi-icam", "DOI ICAM", "DOI",
     "DOI identity and credentialing",
     "access", "DOI network resources", 1, "open", "",
     "", "", ""),
    ("Identity and Access", "usda-eauth", "USDA eAuth", "USDA",
     "USDA identity",
     "access", "USDA network resources", 1, "open", "",
     "", "", ""),
    ("Identity and Access", "max-gov", "Max.gov", "OMB",
     "Cross-agency collaboration",
     "access", "Interagency workspaces", 2, "open", "",
     "", "", ""),
    ("Identity and Access", "hf-token", "Hugging Face token", "Hugging Face",
     "Gated dataset access",
     "access", "PNNL extracts", 1, "go", "VERIFIED WORKING",
     "hf auth login with a read token", "https://huggingface.co/", ""),
    ("Identity and Access", "datagov-key", "api.data.gov key", "GSA",
     "Shared keys across GSA-hosted APIs",
     "access", "GSA-hosted APIs", 2, "go", "VERIFIED WORKING",
     "DEMO_KEY works for testing", "https://api.data.gov/", ""),
    ("Identity and Access", "fedramp", "FedRAMP authorization", "GSA",
     "Cloud service authorization",
     "access", "Hosted components", 2, "open", "",
     "", "", ""),
    ("Identity and Access", "mou", "Interagency agreement / MOU", "Agencies",
     "Legal basis for data access",
     "access", "All SEPI tiers", 1, "open", "",
     "", "", ""),
    ("Identity and Access", "tribal-governance", "Tribal data governance agreement", "Tribes",
     "Consent to include tribal records",
     "access", "Tribal systems of record", 1, "open", "",
     "", "", ""),
]


def row_to_obj(row):
    group, id_, name, owner, holds, tier, applies, priority, light, status, endpoint, url, method = row
    pointer = endpoint if endpoint else ("—" if not url else name)
    note = status or ("Not probed." if light == "open" else "")
    return {
        "id": id_,
        "name": name,
        "owner": owner,
        "group": group,
        "tier": tier,
        "holds": holds,
        "applies": applies,
        "priority": priority,
        "light": light,
        "status": status,
        "method": method,
        "note": note,
        "endpoint": endpoint,
        "pointer": pointer,
        "url": url,
    }


def main():
    connectors = [row_to_obj(r) for r in ROWS]
    ids = [c["id"] for c in connectors]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        raise SystemExit("Duplicate ids: " + ", ".join(dupes))
    payload = {
        "updated": "2026-09-11",
        "source": "SEPI",
        "url": "https://sepi.thermalunderground.org/connectors.json",
        "inventory": "Revised 11 September 2026. Status is what was verified by direct request. Blank status is not probed.",
        "connectors": connectors,
    }
    dest = Path(__file__).resolve().parents[1] / "connectors.json"
    dest.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"{len(connectors)} connectors → {dest}")


if __name__ == "__main__":
    main()
